### ISSUE TITLE
Unable to create new user.

### ISSUE THREAD

**Issue by snulluns** [GPR-ZRH/P4Install#3]
When running the command in Step 2 there's a section where it attempts to create a new User called Perforce. I get the following error lines:

> sudo: adduser: command not found
> sudo: passwd: command not found

This is on a DS218+ running commands through PuTTY.

**Comment by GPR-ZRH** [comment]
Thanks for reporting the issue. We haven't used this script ourselves in a long time because we switched to centos/ubuntu-based servers and Perforce nowadays provides their own Install Scripts.
Because there is no install script for Synology DiskStations, I worked through the issues and the script should now work for you. I did a quick test on my DS1819+ running DSM 6.2.4-25556

Beware that the script currently does not support setting up a ssl connection. You can do that yourself though:
https://community.perforce.com/s/article/2596

Can you check whether the installation process works for you now?
